//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_discription
    {
        public int Employee_id { get; set; }
        public int Emp_type_id { get; set; }
        public System.DateTime Date_of_employment { get; set; }
    
        public virtual Emp_type Emp_type { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
