//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpManagmentEntities : DbContext
    {
        public EmpManagmentEntities()
            : base("name=EmpManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emp_discription> Emp_discription { get; set; }
        public virtual DbSet<Emp_type> Emp_type { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Passport_data> Passport_data { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
