//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_id { get; set; }
        public int Post_id { get; set; }
        public string Employee_name { get; set; }
        public string Employee_surname { get; set; }
        public string Employee_patronymic { get; set; }
        public string Phone_number_emp { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
    
        public virtual Emp_discription Emp_discription { get; set; }
        public virtual Post Post { get; set; }
        public virtual Passport_data Passport_data { get; set; }
    }
}
