//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport_data
    {
        public int Employee_id { get; set; }
        public string Passport_serial { get; set; }
        public string Passport_number { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
